### ISSUE TITLE
I've tried to use the code without efficient results

### ISSUE THREAD

**Issue by vfbsilva** [RonyAbecidan/ManTraNet-pytorch#6]
I've tested it against id cards I have manipulated could we maybe check why it is not working at all? Regions of interest simple do not match the forged sections. CAn I email you the input images?

**Comment by RonyAbecidan** [comment]
This doesn't surprise me. MantraNet have not been trained on fake id cards so it is not really suited to the situation you described. To make it work, you should train it with your own databases of fake id cards so that it suits with your application in the real word.

That being said, training MantraNet is not so easy. In the paper they trained separetely the two core components of this network (feature extraction and anomaly detection) with specific datasets they didn't share so it is not really reproducible. I am going soon to update the repo decoupling these two components so that everyone can try to train it properly !

**Comment by vfbsilva** [comment]
Thanks a lot for the super swift reply. I will be waiting for a chance to train it properly.
